//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebContent {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebContent.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.milestonesys.com.
        /// </summary>
        internal static string BrowserHomeAddress {
            get {
                return ResourceManager.GetString("BrowserHomeAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CompanyLogo {
            get {
                object obj = ResourceManager.GetObject("CompanyLogo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon icon {
            get {
                object obj = ResourceManager.GetObject("icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cascadia Technology.
        /// </summary>
        internal static string PluginCompany {
            get {
                return ResourceManager.GetString("PluginCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4faaaf8f-9286-453f-8599-2555e17e535d.
        /// </summary>
        internal static string PluginId {
            get {
                return ResourceManager.GetString("PluginId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MIPSDK-SiteLicense.
        /// </summary>
        internal static string PluginLicenseType {
            get {
                return ResourceManager.GetString("PluginLicenseType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web Content.
        /// </summary>
        internal static string PluginName {
            get {
                return ResourceManager.GetString("PluginName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to d734ab01-63f1-4e15-9598-0d83b0d4ec86.
        /// </summary>
        internal static string RootItemNodeKind {
            get {
                return ResourceManager.GetString("RootItemNodeKind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 37e27b53-81ff-459e-85fd-64e6e9fbeb7f.
        /// </summary>
        internal static string SharedNodeId {
            get {
                return ResourceManager.GetString("SharedNodeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to b4b361b6-fcd1-47b7-b514-cca934afaac6.
        /// </summary>
        internal static string ViewItemPluginId {
            get {
                return ResourceManager.GetString("ViewItemPluginId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap WebContentIcon {
            get {
                object obj = ResourceManager.GetObject("WebContentIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7c56af89-db44-4c3a-8c70-2527de942756.
        /// </summary>
        internal static string WebContentKind {
            get {
                return ResourceManager.GetString("WebContentKind", resourceCulture);
            }
        }
    }
}
