//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebContent {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebContent.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow audio notifications.
        /// </summary>
        internal static string AllowAudioNotificationsLabel {
            get {
                return ResourceManager.GetString("AllowAudioNotificationsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow Smart Client notification messages to be shown at the top of the current view when this browser instance starts playing audio. These notifications can be used to mute the related browser instance. The web page title will be displayed in the notification to differentiate between multiple browser instances..
        /// </summary>
        internal static string AllowAudioNotificationsToolTip {
            get {
                return ResourceManager.GetString("AllowAudioNotificationsToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow browser to run in background.
        /// </summary>
        internal static string AllowBackgroundBrowserLabel {
            get {
                return ResourceManager.GetString("AllowBackgroundBrowserLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave the browser instance open in the background to improve loading response time. Disabling this will close this browser instance preventing it from using resources in the background..
        /// </summary>
        internal static string AllowBackgroundBrowserToolTip {
            get {
                return ResourceManager.GetString("AllowBackgroundBrowserToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear history now.
        /// </summary>
        internal static string ClearBrowsingDataNowLabel {
            get {
                return ResourceManager.GetString("ClearBrowsingDataNowLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear history on exit.
        /// </summary>
        internal static string ClearBrowsingDataOnExitLabel {
            get {
                return ResourceManager.GetString("ClearBrowsingDataOnExitLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear the browser history, cookies, and all other browsing data when closing Smart Client..
        /// </summary>
        internal static string ClearBrowsingDataOnExitToolTip {
            get {
                return ResourceManager.GetString("ClearBrowsingDataOnExitToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable developer tools (F12).
        /// </summary>
        internal static string EnableDevToolsLabel {
            get {
                return ResourceManager.GetString("EnableDevToolsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable the browser developer tools which can be opened using the F12 keyboard shortcut or the context menu..
        /// </summary>
        internal static string EnableDevToolsToolTip {
            get {
                return ResourceManager.GetString("EnableDevToolsToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide address.
        /// </summary>
        internal static string HideAddressLabel {
            get {
                return ResourceManager.GetString("HideAddressLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide the address in the toolbar. Enable this if you want access to the toolbar, but you do not want the user to have access to the address field..
        /// </summary>
        internal static string HideAddressToolTip {
            get {
                return ResourceManager.GetString("HideAddressToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide toolbar.
        /// </summary>
        internal static string HideToolbarLabel {
            get {
                return ResourceManager.GetString("HideToolbarLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The toolbar is always visible in setup mode. Enable this to hide the toolbar when not in setup mode. Note that with the toolbar hidden, you will not have access to the address bar, or navigation buttons, and you cannot double-click anywhere to maximize the browser view item..
        /// </summary>
        internal static string HideToolbarToolTip {
            get {
                return ResourceManager.GetString("HideToolbarToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.cascadia.tech/.
        /// </summary>
        internal static string HomeAddress {
            get {
                return ResourceManager.GetString("HomeAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string HomeLabel {
            get {
                return ResourceManager.GetString("HomeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Isolate this browser instance.
        /// </summary>
        internal static string IsolateBrowserInstancesLabel {
            get {
                return ResourceManager.GetString("IsolateBrowserInstancesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use a unique browser profile to isolate this browser instance from any others..
        /// </summary>
        internal static string IsolateBrowserInstancesToolTip {
            get {
                return ResourceManager.GetString("IsolateBrowserInstancesToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mute audio.
        /// </summary>
        internal static string MuteAudioLabel {
            get {
                return ResourceManager.GetString("MuteAudioLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mute all audio for this browser instance..
        /// </summary>
        internal static string MuteAudioToolTip {
            get {
                return ResourceManager.GetString("MuteAudioToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase a license.
        /// </summary>
        internal static string PurchaseLicenseLabel {
            get {
                return ResourceManager.GetString("PurchaseLicenseLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://tinyurl.com/cbtxvv76.
        /// </summary>
        internal static string PurchaseLicenseUrl {
            get {
                return ResourceManager.GetString("PurchaseLicenseUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember last address.
        /// </summary>
        internal static string RememberLastAddressLabel {
            get {
                return ResourceManager.GetString("RememberLastAddressLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open this browser instance to the last address instead of the home page..
        /// </summary>
        internal static string RememberLastAddressToolTip {
            get {
                return ResourceManager.GetString("RememberLastAddressToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom level.
        /// </summary>
        internal static string ZoomLevelLabel {
            get {
                return ResourceManager.GetString("ZoomLevelLabel", resourceCulture);
            }
        }
    }
}
